# Generated by Django 5.2.16 on 2026-07-25 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, help_text='e.g. Computer Science', max_length=120)),
                ('year_of_study', models.CharField(blank=True, help_text='e.g. 1st Year, 2nd Year', max_length=40)),
                ('student_id', models.CharField(blank=True, max_length=50, verbose_name='Student ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
